apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-devops-meeting-deployment
  namespace: dev-namespace
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dev-devops-meeting-deployment
  template:
    metadata:
      labels:
        app: dev-devops-meeting-deployment
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - proxmox-ser
      containers:
      - name: dev-devops-meeting-deployment
        image: idrisniyi94/devops-meeting:dev
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000
