apiVersion: v1
kind: Service
metadata:
  name: prod-devops-meeting-service
  namespace: prod-namespace
spec:
  selector:
    app: prod-devops-meeting-deployment
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 32002
  type: NodePort
