apiVersion: v1
kind: Service
metadata:
  name: qa-devops-meeting-service
  namespace: qa-namespace
spec:
  selector:
    app: qa-devops-meeting-deployment
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 32000
  type: NodePort
